### ISSUE TITLE
[Bug] @import statement in <style> section does not work

### ISSUE THREAD

**Issue by scriptPilot** [lc60005457/parcel-plugin-vue#21]
**Works**:

sfc.vue
```css
<style>
  body {
    margin-top: 50px;
  }
</style>
```

**Does not work**:

sfc.vue
```css
<style>
  @import './style.css';
</style>
```

style.css
```css
body {
    margin-top: 50px;
}
```
