### ISSUE TITLE
How to use assets within `style` part?

### ISSUE THREAD

**Issue by PeachScript** [lc60005457/parcel-plugin-vue#31]
Hello @BoltDoggy , thanks for your great plugin!

When I use assets within `style` part, for example:

```css
.logo {
  background: url('../assets/images/logo.png') no-repeat center/100%;
}
```

It cannot resolve assets for me, and parcel will not generate the assets, so...do you have any idea about it?

| Software                | Version(s) |
| ------------------ | ---------- |
| parcel-plugin-vue | 1.5.0
| Parcel                     | 1.6.2
| Vue                         | 2.5.13
| Node                      | 9.3.0
| npm/Yarn               | 5.6.0 (npm)
| Operating System | macOS Sierra 10.12.6 with Chrome 64
